version: '3'
services:
  postgres:
    image: postgis/postgis:12-master
    environment:
      - POSTGRES_DB=xrn
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres:/var/lib/postgresql/data
